# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff51f9a1e79281818758177c0c1f761ee5e47b569ecc5aa4ef49ee032d113728bfa24c53a8261792f5beea063e452d624cc106c4a6d2b91e6978003cab477ad1

test:
  secret_key_base: 731be27ce95216e7f5d1c21f015890617205c57b371792528729b008f119c98652d14fbb40c2ee8c1fae9a60adb318d0fa8d99b1f493e8c02552bf823881d563

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
